### ISSUE TITLE
How to use the key attribute?

### ISSUE THREAD

**Issue by dpretty** [Ziggeo/vue-ziggeo#15]
For our application we need to set a key attribute when recording videos.

The key attribute has been disabled because of conflict with the reserved Vue keyword.

https://github.com/Ziggeo/vue-ziggeo/blob/ba494dee65290a48d9cfe9bfb6694a18ac57d84f/src/components/constants.js#L79

Is there any workaround? e.g. map the `key` attribute to another name within Vue so that a key value can be used with the API?

**Comment by sambua** [comment]
Hi @dpretty, 

Will look for workaround options, if possible will make changes shortly. 

Thanks.

**Comment by dpretty** [comment]
Hi @sambua , 

were you able to find any workaround for this one?

Perhaps if the `key` attribute was named something like `ziggeoKey` in vue-ziggeo/src/components/constants.js and then was remapped back to `key` when passed to back to the ziggeo API in  https://github.com/Ziggeo/vue-ziggeo/blob/5a398311d38246672dbbb9dd9b4947b0438926f3/src/components/ZiggeoRecorder/ZiggeoRecorder.vue#L24  ?

Thanks.

**Comment by sambua** [comment]
Hello @dpretty , 

Sorry it took some time, could you please check newest version `2.2.0` ? 

Thanks

**Comment by sambua** [comment]
Closing based on #16
