### ISSUE TITLE
Playlist support

### ISSUE THREAD

**Issue by dpretty** [Ziggeo/vue-ziggeo#18]
It appears playlists are not currently supported in Vue (i.e. no reference to playlist parameter in constants.js). 

Would it be possible to add playlist support to the Vue library? Is it as simple as just adding `playlist` in `constants.js` ?

Thanks

**Comment by sambua** [comment]
Hello Dave,

Yes, it's possible in the future if you require it, but for know you can upgrade to `vue-ziggeo@2.3.0`

**Comment by sambua** [comment]
#19
