### ISSUE TITLE
Number of recordings not being updated

### ISSUE THREAD

**Issue by freitasskeeled** [Ziggeo/vue-ziggeo#5]
Hey,

The title says pretty much all the information. We are using version 0.2.1.

Basically, the number of recordings is not being updated (sometimes).

Cheers.

**Comment by sambua** [comment]
Dear Rui ( @freitasskeeled ),

Sorry you mean, a number of recorded videos in the application account part? I mean after you login to https://ziggeo.com account page?

Also, could you please advice browser with you're testing it?

Thanks in advance,
Cheers

**Comment by freitasskeeled** [comment]
Hey again,

So we noticed that the problem is not related to the recordings. 

We are investigating the issue and we will get back to you (if needed).

Thank you and sorry for the trouble. You may close this.

**Comment by sambua** [comment]
Hi Rui ( @freitasskeeled ),

No problem and thanks for the investigation.

Cheers
